import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Navroop Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
      />
      <body className={inter.className}>
        <header className="sticky top-0 z-10">
          <section className="mx-auto flex max-w-4xl items-center justify-center"></section>
        </header>
        {children}
      </body>
    </html>
  );
}
